name: Instagram AI Bot
on:
  workflow_dispatch:      # manuel çalıştırmak için
  schedule:
    - cron: '0 9 * * *'   # her sabah 09:00’da otomatik çalışsın

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
      - name: Upload resim
        uses: actions/upload-artifact@v4
        with:
          name: instagram-post
          path: instagram_post.png
